version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
    - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - 1337:80
    depends_on:
      - web
  celery:
    build: .
    command: celery --app=project worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis

  redis:
    image: redis:6-alpine
  dashboard:
    build: .
    command: celery flower -A project --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    env_file:
      - ./.env.prod
    depends_on:
      - web
      - redis
      - celery
  celery-beat:
    build: .
    command: celery -A project beat -l info
    volumes:
      - .:/usr/src/app/
    env_file:
      - ./.env.prod
    depends_on:
      - redis

volumes:
  postgres_data:
  static_volume:
